[phases.setup]
nixPkgs = [
    "chromium",
    "nss",
    "nspr",
    "atk",
    "at-spi2-atk",
    "cups",
    "libdrm",
    "libxkbcommon",
    "pango",
    "cairo",
    "libgbm",
    "alsa-lib",
    "expat",
    "mesa"
]